version: 2.1

workflows:
  docker-push-sonobuoy-plugin:
    jobs:
      - build:
          context: architect

jobs:
  build:
    docker:
      - image: docker:20
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Build application Docker image
          command: |
            docker build -t "quay.io/giantswarm/sonobuoy-plugin:${CIRCLE_BRANCH}" .
      - run:
          name: Authenticate to container registry
          command: |
            echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin "quay.io"
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker tag "quay.io/giantswarm/sonobuoy-plugin:${CIRCLE_BRANCH}" "quay.io/giantswarm/sonobuoy-plugin:latest"
              docker push "quay.io/giantswarm/sonobuoy-plugin:latest"
            else
              docker push "quay.io/giantswarm/sonobuoy-plugin:${CIRCLE_BRANCH}"
            fi
